 CREATE TABLE custom_issuelink (created_at timestamp with time zone, case_id_1 character varying(64), id bigint, link_type character varying(32), case_id_2 character varying(64));
 CREATE TABLE approval_audit_log (tool_params jsonb, decided_at timestamp with time zone, summary text, conversation_id character varying(256), created_at timestamp with time zone, id integer, tool_name character varying(256), tier character varying(32), approver_id character varying(256), request_id character varying(64), status character varying(32), requester_role character varying(32));
 CREATE TABLE custom_processedmessage (processed_at timestamp with time zone, id bigint, teams_message_id character varying(256), thread_id character varying(256));
 CREATE TABLE custom_conversationstate (thread_id character varying(256), last_bot_message_id character varying(256), updated_at timestamp with time zone, active_case_id character varying(64), id bigint, last_user_message_id character varying(256));
 CREATE TABLE django_migrations (app character varying(255), name character varying(255), id integer, applied timestamp with time zone);
 CREATE TABLE workflow_catalog (category character varying(128), org_code character varying(64), description text, workflow_id character varying(64), workflow_name character varying(512), fetched_at timestamp with time zone, parameters jsonb, raw_data jsonb, active boolean);
 CREATE TABLE issue_registry (updated_at timestamp with time zone, conversation_id character varying(256), issue_data jsonb, issue_id character varying(64));
 CREATE TABLE conversation_state (updated_at timestamp with time zone, is_human_handoff boolean, user_role character varying(32), conversation_id character varying(256), phase character varying(32), active_issue_id character varying(64), summary text, state_data jsonb, user_id character varying(256));
 CREATE TABLE custom_case (owner_type character varying(32), workflows_involved jsonb, resolved_at timestamp with time zone, case_id character varying(64), latest_plan_json jsonb, error_signatures jsonb, updated_at timestamp with time zone, created_at timestamp with time zone, plan_version integer, user_type character varying(32), planner_state_json jsonb, recurrence_count integer, thread_id character varying(256), id bigint, state character varying(64), resolution_summary text, owner_team character varying(64), ticket_id character varying(128));
 CREATE TABLE tool_execution_log (tool_name character varying(256), id bigint, agent_id character varying(128), duration_ms integer, success boolean, error_message text, result jsonb, params jsonb, created_at timestamp with time zone, conversation_id character varying(256));
 CREATE TABLE custom_approval (requested_to jsonb, case_id character varying(64), reason text, decided_at timestamp with time zone, plan_version integer, id bigint, status character varying(32), decided_by character varying(256), created_at timestamp with time zone);
 CREATE TABLE user_registry (metadata jsonb, updated_at timestamp with time zone, created_at timestamp with time zone, user_name character varying(256), user_id character varying(256), user_email character varying(256), user_role character varying(32), user_team character varying(128));
 CREATE TABLE user_feedback (rating integer, id integer, user_id character varying(256), created_at timestamp with time zone, metadata jsonb, comments text, conversation_id character varying(256));
 CREATE TABLE chat_messages (metadata jsonb, conversation_id character varying(256), content text, id integer, role character varying(32), created_at timestamp with time zone);
 CREATE TABLE rag_documents (embedding USER-DEFINED, content text, tsv tsvector, metadata jsonb, id text, collection text, created_at timestamp with time zone);

