
import sys
import os
import io
import json
from unittest.mock import MagicMock, patch

# Force UTF-8 for stdout
if sys.stdout.encoding != 'utf-8':
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# Mock llm_client
captured_calls = []
class MockLLM:
    def chat(self, prompt, **kwargs):
        # We need to see if the system prompt contains Rule 16
        # The prompt passed to chat is the user message + history
        # The system prompt is passed in kwargs or pre-configured
        return "MOCK_RESPONSE"

import config.llm_client
config.llm_client.llm_client = MockLLM()

from agents.orchestrator import Orchestrator
from state.conversation_state import ConversationState

def test_proactive_prompt():
    orch = Orchestrator()
    state = ConversationState()
    state.conversation_id = "test-conv"
    
    # We want to check the system prompt generated by _build_system_prompt
    from state.issue_tracker import IssueTracker
    tracker = IssueTracker(state.conversation_id)
    
    print("Testing Orchestrator System Prompt for Rule 16...")
    system_prompt = orch._build_system_prompt(state, tracker)
    
    if "16. **PROACTIVE DIAGNOSTIC DISCOVERY**" in system_prompt:
        print("SUCCESS: Rule 16 found in system prompt.")
    else:
        print("FAILURE: Rule 16 NOT found in system prompt.")
        
    if "AMBIGUITY RESOLUTION" in system_prompt:
        print("SUCCESS: Ambiguity Resolution instructions found.")
    else:
        print("FAILURE: Ambiguity Resolution instructions NOT found.")

    # Check if it mentions specific tools to use
    discovery_tools = ["t4_check_agent_status", "list_recent_failures", "ae.agent.list_running"]
    found_tools = [t for t in discovery_tools if t in system_prompt]
    print(f"Discovery tools mentioned: {found_tools}")
    
    if "PARAMETER PROACTIVE GATHERING" in system_prompt:
        print("SUCCESS: Parameter Proactive Gathering sub-rule found.")
    else:
        print("FAILURE: Parameter Proactive Gathering sub-rule NOT found.")

    if "ISO format" in system_prompt and "24 hours" in system_prompt:
        print("SUCCESS: Explicit date range instructions found.")
    else:
        print("FAILURE: Explicit date range instructions NOT found.")

if __name__ == "__main__":
    test_proactive_prompt()
