FROM python:3.9-slim-buster

# Install dependencies
RUN apt-get update
RUN apt-get install -y build-essential
# To be able to run ps command
RUN apt-get update && apt-get install -y procps
RUN apt-get update && apt-get install -y curl
RUN apt-get update && apt-get install -y sudo

# Add SQL Server ODBC Driver 17
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update
RUN ACCEPT_EULA=Y apt-get install -y --allow-unauthenticated msodbcsql17
RUN ACCEPT_EULA=Y apt-get install -y --allow-unauthenticated mssql-tools
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc

RUN /usr/local/bin/python -m pip install --upgrade pip
COPY ./ /opt/aistudiobot
WORKDIR /opt/aistudiobot
RUN pip install -r requirements.txt --no-cache-dir

# start server
EXPOSE 3978
STOPSIGNAL SIGTERM
#COPY docker-entrypoint.dev.sh /
RUN chmod +x docker-entrypoint.dev.sh

###############################################################
# add non privileged user
###############################################################
RUN addgroup --system aistudio_group && adduser --system --ingroup aistudio_group aistudio
RUN /bin/chown aistudio:aistudio_group -R /opt/aistudiobot
RUN adduser aistudio sudo
RUN echo 'aistudio ALL=(ALL) NOPASSWD: /bin/chown, /usr/sbin/deluser' >> /etc/sudoers

###############################################################
# set user
###############################################################
USER aistudio

ENTRYPOINT ["/opt/aistudiobot/docker-entrypoint.dev.sh"]
