trigger: none
pr:
- master
- develop
schedules:
- cron: '0 0 1,15 * *'
  displayName: Security pipeline
  branches:
    include:
    - develop
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/develop
jobs:
- job: CBWSSecurityJob
  displayName: CBWS Security Job
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    clean: true
    fetchTags: true
  - task: AzureCLI@2
    displayName: Start SonarQube VM
    inputs:
      connectedServiceNameARM: fc39ff94-e9ab-4ec7-be62-50b022dba573
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: >-
        az vm start -g SonarQube-RG -n sonarqube-vm

        timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}''  http://aesonarqube.eastus.cloudapp.azure.com/api/server/version)" != "200" ]]; do sleep 5; done'
  - task: SonarQubePrepare@5
    displayName: Prepare analysis on SonarQube
    inputs:
      SonarQube: 01b2c730-186f-4875-861c-950d34160a17
      scannerMode: CLI
      configMode: manual
      cliProjectKey: chatbot-webservice_chatbot-webservice
  - task: SonarQubeAnalyze@5
    displayName: Run Code Analysis
  - task: SonarQubePublish@5
    displayName: Publish Quality Gate Result
  - task: AzureCLI@2
    displayName: Stop SonarQube VM
    inputs:
      connectedServiceNameARM: fc39ff94-e9ab-4ec7-be62-50b022dba573
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: az vm deallocate -g SonarQube-RG -n sonarqube-vm
  - task: Bash@3
    displayName: Install python3.9 and requirements for Snyk
    inputs:
      targetType: inline
      script: >
        sudo apt update

        sudo apt install software-properties-common

        sudo add-apt-repository ppa:deadsnakes/ppa

        sudo apt install python3.9 python3.9-dev

        python3.9 -V

        python3.9 -m pip install --upgrade pip
        python3.9 -m pip -V

        cd $(Build.SourcesDirectory)

        python3.9 -m pip install -r requirements.txt
  - task: SnykSecurityScan@1
    displayName: Snyk scan for open source vulnerabilities
    inputs:
      serviceConnectionEndpoint: 440d533d-4ba8-4122-8666-53586e07db9b
      projectName: Requirements
      additionalArguments: --command=/usr/bin/python3.9 --skip-unresolved
...
